// Items dataset for Campaign Companion
const RARITIES = [
  { id: "common",     label: "Common",     color: "var(--rarity-common)" },
  { id: "uncommon",   label: "Uncommon",   color: "var(--rarity-uncommon)" },
  { id: "rare",       label: "Rare",       color: "var(--rarity-rare)" },
  { id: "epic",       label: "Epic",       color: "var(--rarity-epic)" },
  { id: "legendary",  label: "Legendary",  color: "var(--rarity-legendary)" },
];

const ITEM_TYPES = [
  { id: "weapon",     label: "Weapon" },
  { id: "armor",      label: "Armor" },
  { id: "artifact",   label: "Artifact" },
  { id: "consumable", label: "Consumable" },
  { id: "misc",       label: "Misc" },
];

const PARTY = [
  { id: "kael",   name: "Kael Vance",     role: "Warden",      initials: "KV", tone: "#7a9c5a" },
  { id: "sera",   name: "Sera Ilenne",    role: "Stormcaller", initials: "SI", tone: "#5a7a9c" },
  { id: "thom",   name: "Thom Underbrook",role: "Trickster",   initials: "TU", tone: "#c9a25b" },
  { id: "vex",    name: "Vex of Ash",     role: "Beastbound",  initials: "VA", tone: "#8a3a3a" },
  { id: "party",  name: "Party Stash",    role: "Shared",      initials: "★",  tone: "#8a8676" },
];

const LORE_ENTRIES = [
  { id: "l1", title: "The Sundered Crown",        kind: "Artifact Lore" },
  { id: "l2", title: "House Veyrun, Fall of",     kind: "House" },
  { id: "l3", title: "The Glassmere Pact",        kind: "Treaty" },
  { id: "l4", title: "Wyrmsong Hollow",           kind: "Location" },
  { id: "l5", title: "The Pale Choir",            kind: "Faction" },
  { id: "l6", title: "Embergloss Forge, ruins of",kind: "Location" },
  { id: "l7", title: "Saint Orenna the Quiet",    kind: "Figure" },
];

const ITEMS = [
  {
    id: "i1",
    name: "Ashforged Cleaver",
    type: "weapon",
    rarity: "rare",
    dmOnly: false,
    tagline: "Forged in the cooling cinders of the Embergloss.",
    description: "A heavy cleaver hammered from cooled forge-slag, still warm to the touch on cold mornings. Its edge takes a strange polish — neither steel nor iron — and sings faintly when carried near old fires.",
    properties: [
      { k: "Damage",            v: "1d8 slashing" },
      { k: "Weight",            v: "4 lb" },
      { k: "Requires Attunement", v: "No" },
    ],
    lore: "l6",
    inventory: [{ who: "kael", qty: 1 }],
  },
  {
    id: "i2",
    name: "The Sundered Crown",
    type: "artifact",
    rarity: "legendary",
    dmOnly: true,
    tagline: "Three pieces. Three oaths. One ruin.",
    description: "What remains of the Crown of Veyrun, broken when the last queen refused the Pale Choir. The fragments hum to one another across distance, and to those who hold them, the dead speak — sometimes truly.",
    properties: [
      { k: "Fragments",          v: "1 of 3 recovered" },
      { k: "Resonance",          v: "Audible at moonrise" },
      { k: "Requires Attunement", v: "Yes (sworn oath)" },
      { k: "Curse",              v: "Concealed from PCs" },
    ],
    lore: "l1",
    inventory: [{ who: "party", qty: 1 }],
  },
  {
    id: "i3",
    name: "Tidewatcher's Mantle",
    type: "armor",
    rarity: "epic",
    dmOnly: false,
    tagline: "Salt-stiff and shimmering, woven from kelp-silk.",
    description: "A hooded mantle taken from a drowned Glassmere envoy. The cloth never dries fully, and breathes when no wind moves.",
    properties: [
      { k: "Armor Class Bonus", v: "+1" },
      { k: "Resistance",        v: "Cold" },
      { k: "Requires Attunement", v: "Yes" },
    ],
    lore: "l3",
    inventory: [{ who: "sera", qty: 1 }],
  },
  {
    id: "i4",
    name: "Vial of Hollow Light",
    type: "consumable",
    rarity: "uncommon",
    dmOnly: false,
    tagline: "Bottled glow, rendered from witchmoss.",
    description: "Snaps when pressed; sheds a pale, shadowless light for an hour. Moths avoid it.",
    properties: [
      { k: "Charges", v: "1" },
      { k: "Duration", v: "1 hour" },
    ],
    lore: null,
    inventory: [{ who: "thom", qty: 3 }, { who: "party", qty: 2 }],
  },
  {
    id: "i5",
    name: "Saint Orenna's Sigh",
    type: "consumable",
    rarity: "rare",
    dmOnly: true,
    tagline: "A single breath, kept in waxed glass.",
    description: "Said to be the last exhalation of a saint who refused to speak in life. Inhaling restores composure to the unbalanced — or so claim the relic-priests of the Quiet Order.",
    properties: [
      { k: "Charges", v: "1" },
      { k: "Effect",  v: "Restores resolve" },
    ],
    lore: "l7",
    inventory: [{ who: "party", qty: 1 }],
  },
  {
    id: "i6",
    name: "Wyrmsong Lockpicks",
    type: "misc",
    rarity: "uncommon",
    dmOnly: false,
    tagline: "Cut from a dragon's tooth, set in pearwood.",
    description: "A slender set of picks that hum at the throat of a willing lock.",
    properties: [
      { k: "Bonus",   v: "+2 on lockpicking attempts" },
      { k: "Weight",  v: "0.2 lb" },
    ],
    lore: "l4",
    inventory: [{ who: "thom", qty: 1 }],
  },
  {
    id: "i7",
    name: "Plain Iron Shortsword",
    type: "weapon",
    rarity: "common",
    dmOnly: false,
    tagline: "Reliable, unremarkable, sharp enough.",
    description: "A municipal-issue shortsword; the maker's mark has been filed off.",
    properties: [
      { k: "Damage", v: "1d6 piercing" },
      { k: "Weight", v: "2 lb" },
    ],
    lore: null,
    inventory: [{ who: "vex", qty: 1 }],
  },
  {
    id: "i8",
    name: "Choirbound Censer",
    type: "artifact",
    rarity: "epic",
    dmOnly: true,
    tagline: "Smoke that listens.",
    description: "A hand-censer in tarnished brass. The smoke does not rise; it gathers, and turns where speech is hidden.",
    properties: [
      { k: "Charges",   v: "3 / day" },
      { k: "Reveals",   v: "Concealed truths within 30 ft" },
      { k: "Faction Tie", v: "The Pale Choir" },
    ],
    lore: "l5",
    inventory: [{ who: "party", qty: 1 }],
  },
  {
    id: "i9",
    name: "Ledger of Small Debts",
    type: "misc",
    rarity: "common",
    dmOnly: false,
    tagline: "A hand-bound book, half-filled.",
    description: "Names, sums, and a few crossed-out grudges. Useful in any town with a memory.",
    properties: [
      { k: "Pages used", v: "47 of 120" },
    ],
    lore: null,
    inventory: [{ who: "thom", qty: 1 }],
  },
  {
    id: "i10",
    name: "Veyrun Signet Ring",
    type: "misc",
    rarity: "rare",
    dmOnly: false,
    tagline: "A house-mark from a fallen line.",
    description: "Heavy gold, with the Veyrun thorn-and-sun stamped deep. Recognized by certain old servants — and certain old enemies.",
    properties: [
      { k: "Material",   v: "Gold, ~1 oz" },
      { k: "Recognition", v: "House Veyrun" },
    ],
    lore: "l2",
    inventory: [{ who: "kael", qty: 1 }],
  },
  {
    id: "i11",
    name: "Bramblewax Candle",
    type: "consumable",
    rarity: "common",
    dmOnly: false,
    tagline: "Burns blue in haunted air.",
    description: "Cheap, cheerful, and surprisingly accurate.",
    properties: [
      { k: "Burn time", v: "6 hours" },
    ],
    lore: null,
    inventory: [{ who: "party", qty: 4 }],
  },
  {
    id: "i12",
    name: "Glassmere Tide-Glass",
    type: "artifact",
    rarity: "legendary",
    dmOnly: false,
    tagline: "A spyglass that sees what was, when turned to the sea.",
    description: "Brass-bound, cold to the cheek. Looking through it at any body of saltwater shows the surface as it was, one tide ago.",
    properties: [
      { k: "Range",   v: "1 mile" },
      { k: "Window",  v: "Previous tide" },
      { k: "Requires Attunement", v: "Yes" },
    ],
    lore: "l3",
    inventory: [{ who: "sera", qty: 1 }],
  },
];

window.CC_DATA = { RARITIES, ITEM_TYPES, PARTY, LORE_ENTRIES, ITEMS };
